# SPDX-FileCopyrightText: 2025-2026 Scarlett Moore <sgmoore@kde.org>
#
# SPDX-License-Identifier: CC0-1.0
---
name: kongress
confinement: strict
grade: stable
base: core24
adopt-info: kongress
apps:
  kongress:
    extensions:
      - kde-neon-6
    common-id: org.kde.kongress.desktop
    desktop: usr/share/applications/org.kde.kongress.desktop
    command: usr/bin/kongress
    plugs:
      - home
      - audio-playback
    environment:
      ALSA_CONFIG_PATH: "$SNAP/kf6/etc/asound.conf"
      QML_IMPORT_PATH: "$SNAP/kf6/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qml:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qml"
layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib
slots:
  session-dbus-interface:
    interface: dbus
    name: org.kde.kongress
    bus: session
parts:
  kosmindoormap:
    after:
      - kpublictransport
      - kopeninghours
    source: https://invent.kde.org/libraries/kosmindoormap.git
    source-branch: master
    plugin: cmake
    build-snaps:
      - kde-qt6-core24-sdk/latest/beta
      - kf6-core24-sdk/latest/beta
    build-packages:
      - librecast-dev
    stage-packages:
      - rsync
      - libpopt0
      - librecast1
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_TESTING=OFF
    override-stage: |
      env
      craftctl default
      rsync -a --ignore-existing $CRAFT_PART_INSTALL/ /
  kpublictransport:
    source: https://invent.kde.org/libraries/kpublictransport.git
    plugin: cmake
    source-branch: master
    build-snaps:
      - kde-qt6-core24-sdk/latest/beta
      - kf6-core24-sdk/latest/beta
    build-packages:
      - libnm-dev
      - libgio3.0-cil-dev
    stage-packages:
      - rsync
      - libpopt0
      - libnm0
      - libgio3.0-cil
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_TESTING=OFF
    override-stage: |
      craftctl default
      rsync -a --ignore-existing $CRAFT_PART_INSTALL/ /
  kopeninghours:
    source: https://invent.kde.org/libraries/kopeninghours.git
    plugin: cmake
    source-branch: master
    build-snaps:
      - kde-qt6-core24-sdk/latest/beta
      - kf6-core24-sdk/latest/beta
    build-packages:
      - bison
      - libboost-all-dev
    stage-packages:
      - rsync
      - libpopt0
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_TESTING=OFF
    override-stage: |
      craftctl default
      rsync -a --ignore-existing $CRAFT_PART_INSTALL/ /
  kongress:
    after:
      - kosmindoormap
      - kpublictransport
      - kopeninghours
    parse-info:
      - usr/share/metainfo/org.kde.kongress.appdata.xml
    plugin: cmake
    source: .
    source-type: local
    build-snaps:
      - kde-qt6-core24-sdk/latest/beta
      - kf6-core24-sdk/latest/beta
    build-packages:
      - libxkbcommon-dev
      - osmctools
      - libprotobuf-dev
      - libpulse0
    stage-packages:
      - libxkbcommon0
      - osmctools
      - libprotobuf32t64
      - libpulse0
      - libasound2
      - libasound2-plugins
      - libasound2-data
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_TESTING=OFF
    prime:
      - -usr/lib/*/cmake/*
      - -usr/include/*
      - -usr/share/ECM/*
      - -usr/share/man/*
      - -usr/bin/X11
      - -usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0
      - -usr/lib/aspell/*
      - -usr/share/lintian
  gpu-2404:
    after: [kongress]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
  cleanup:
    after:
      - kongress
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24
    override-prime: |
      set -eux
      for snap in "core24" "kf6-core24"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
      done
